CREATE DATABASE IF NOT EXISTS bdi_fp_dev;
USE bdi_fp_dev;

CREATE TABLE IF NOT EXISTS bdi_acc_company (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    taxId VARCHAR(255),
    type TINYINT,
    companyNameTh VARCHAR(255),
    companyName VARCHAR(255),
    company_status TINYINT,
    register_date VARCHAR(20),
    typeofService VARCHAR(255),
    subtypeofService VARCHAR(255),
    additionalInfo TEXT,
    location VARCHAR(255),
    city VARCHAR(255),
    district VARCHAR(255),
    subdistrict VARCHAR(255),
    zip VARCHAR(20),
    country VARCHAR(255),
    status TINYINT,
    website VARCHAR(255),
    officeNumber VARCHAR(50),
    phoneNumber VARCHAR(50),
    faxNumber VARCHAR(50),
    is_tech TINYINT(1) DEFAULT 0,
    typeofServiceNonTech VARCHAR(255),
    typeofServiceNonTechOtherName VARCHAR(255),
    subtypeofServiceNonTech VARCHAR(255),
    registerCapital DOUBLE,
    oldTaxId VARCHAR(255),
    objective TEXT,
    financeYearLatestRecord VARCHAR(20),
    is_verified TINYINT(1) DEFAULT 0
);